name: Generate Partonic Mellin results at LO/NLO

on:
  push:
    branches:
      - '**'
      - '!master'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
    defaults:
      run:
        shell: bash --login {0}
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python & PIP
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install meson & ninja
      env:
        repo_token: ${{ secrets.CML }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install meson ninja

    - name: Install dependencies & HpT-MON
      run: |

        # make scripts executable
        chmod +x install-yaml.sh
        chmod +x install-lhapdf.sh
        chmod +x install-cuba.sh

        # install dependencies
        echo "$PWD"
        echo "[+] Install YAML:"
        source install-yaml.sh
        echo "[+] Install LHAPDF:"
        echo "$PWD"
        source install-lhapdf.sh
        echo "[+] Install LHHAPDF:"
        ./install-cuba.sh
        echo "[+] Install GSL:"
        sudo apt-get install libgsl-dev
        
        # install hpt-mon
        echo "[+] Install HpT-MON:"
        meson setup builddir
        cd builddir
        meson compile

        pkg-config --libs yaml-cpp
        echo "[+] Run LO results:"
        ./higgs ../runcards/higgspt-partonic-gg-lo.yaml.yaml
        ./higgs ../runcards/higgspt-hadronic-gg-lo.yaml.yaml
        echo "[+] Run NLO results:"
        ./higgs ../runcards/higgspt-partonic-gg-nlo.yaml.yaml
        ./higgs ../runcards/higgspt-hadronic-gg-nlo.yaml.yaml

        mkdir -p results
        echo "Bot report from $(git rev-parse --short HEAD)" >> results/report.md

        # fetch full hadronic results
        echo '<details markdown="1">' >> results/report.md
        echo ' ' >> results/report.md
        echo '<summary style="font-weight:bold">Full hadronic</summary>' >> results/report.md
        echo "#### LO results (higgspt-partonic-gg-lo.yaml):" >> results/report.md
        cat hadronic_LO_gg_channel.dat | tail -n+10 >> results/report.md
        echo "#### NLO results (higgspt-partonic-gg-nlo.yaml):" >> results/report.md
        cat hadronic_NLO_gg_channel.dat | tail -n+10 >> results/report.md
        echo '</details>' >> results/report.
        echo ' ' >> results/report.md

        # fetch Mellin partonic results
        echo '<details markdown="1">' >> results/report.md
        echo ' ' >> results/report.md
        echo '<summary style="font-weight:bold">Mellin Partonic</summary>' >> results/report.md
        echo "#### LO results (higgspt-partonic-gg-lo.yaml):" >> results/report.md
        cat partonic_LO_gg_channel.dat | tail -n+10 >> results/report.md
        echo "#### NLO results (higgspt-partonic-gg-nlo.yaml):" >> results/report.md
        cat partonic_NLO_gg_channel.dat | tail -n+10 >> results/report.md
        echo '</details>' >> results/report.md

    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: builddir/results/

    - uses: actions/download-artifact@v2
      with:
        name: artifact

    - name: Post results as comment
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.HPT_MON }}
      with:
        path: builddir/results/report.md
